#!/usr/bin/env bash
# Usage: bazelenv version-file [<dir>]
# Summary: Detect the file that sets the current bazelenv version
set -e
[ -n "$BAZELENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -s "${root}/.bazel-version" ]; then
      echo "${root}/.bazel-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$BAZELENV_DIR" || {
    [ "$BAZELENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${BAZELENV_ROOT}/version"
fi
