#!/usr/bin/env bash
# Summary: Show the current bazel version and its origin
#
# Shows the currently selected bazel version and how it was selected.
# To obtain only the version string, use `bazelenv version-name'.

set -e
[ -n "$BAZELENV_DEBUG" ] && set -x

echo "$(bazelenv-version-name) (set by $(bazelenv-version-origin))"
