#!/usr/bin/env bash
# Usage: bazelenv completions <command> [arg1 arg2...]

set -e
[ -n "$BAZELENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  bazelenv-help --usage completions >&2
  exit 1
fi

# Provide bazelenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec bazelenv-commands
fi

COMMAND_PATH="$(command -v "bazelenv-$COMMAND" || command -v "bazelenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide bazelenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
