#!/usr/bin/env bash
# Summary: Show the current bazel version
set -e
[ -n "$BAZELENV_DEBUG" ] && set -x

if [ -z "$BAZELENV_VERSION" ]; then
  BAZELENV_VERSION_FILE="$(bazelenv-version-file)"
  BAZELENV_VERSION="$(bazelenv-version-file-read "$BAZELENV_VERSION_FILE" || true)"
fi

if [ -z "$BAZELENV_VERSION" ] || [ "$BAZELENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${BAZELENV_ROOT}/versions/${version}" ]
}

if version_exists "$BAZELENV_VERSION"; then
  echo "$BAZELENV_VERSION"
elif version_exists "${BAZELENV_VERSION#bazel-}"; then
  echo "${BAZELENV_VERSION#bazel-}"
else
  echo "bazelenv: version \`$BAZELENV_VERSION' is not installed (set by $(bazelenv-version-origin))" >&2
  exit 1
fi
