#!/usr/bin/env bash
# Usage: bazelenv uninstall <version>
# Summary: Uninstall the specified version of bazel

[ -n "${BAZELENV_DEBUG}" ] && set -x
source ${BAZELENV_ROOT}/libexec/helpers.sh

[ ${#} -gt 1 ] && error_and_die "usage: bazelenv uninstall [<version>]"

declare version

if [ -z "${1}" ]; then
  version_file="$(bazelenv-version-file)"
  if [ "${version_file}" != "${BAZELENV_ROOT}/version" ];then
    version="$(cat ${version_file} || true)"
  fi
else
  version="${1}"
fi

[ -n "${version}" ] || error_and_die "Version is not specified"

dst_path="${BAZELENV_ROOT}/versions/${version}"
if [ -f "${dst_path}/bazel" ]; then
  info "Uninstall bazel v${version}"
  rm -r "${dst_path}"
  info "\033[0;32mbazel v${version} is successfully uninstalled\033[0;39m"
fi
