#!/usr/bin/env bash
# Usage: bazelenv install <version>
# Summary: Install the specified version of bazel

[ -n "${BAZELENV_DEBUG}" ] && set -x
source ${BAZELENV_ROOT}/libexec/helpers.sh

[ "${#}" -gt 1 ] && error_and_die "usage: bazelenv install [<version>]"

declare version

if [ -z "${1}" ]; then
  version_file="$(bazelenv-version-file)"
  if [ "${version_file}" != "${BAZELENV_ROOT}/version" ]; then
    version="$(cat ${version_file} || true)"
  fi
else
  version="${1}"
fi

BAZEL_REPO='https://api.github.com/repos/bazelbuild/bazel/releases'
test "$1" == "--list" -o "$1" == "-l" && {
  eval which {wget,curl,jq} &>/dev/null || { echo Please install wget,curl,jq ; exit 0; }
  next="${BAZEL_REPO}?simple=yes&per_page=100&page="
  page="1"
  while true; do
    versions=$(wget -qO- "${next}${page}" | jq -r '.[].tag_name')
    echo $versions
    export next=$(curl -sSLIvk "${next}${page}" 2>&1 | grep -m1 link | sed 's|.*page=\(.*\)>;|\1|g'|xargs -n1 )
    echo $next
    page=$(cut -d' ' -f1 <<<$next)
    grep -q last <<<${next} && break
  done
  exit 0
}

#dst_path="${BAZELENV_ROOT}/versions/${version}/bin"
dst_path="${BAZELENV_ROOT}/versions/${version}"
if [ -f "${dst_path}/bazel" ]; then
  echo "bazel v${version} is already installed"
  exit 0
fi

info "Installing bazel v${version}"
mkdir -p "${dst_path}" || error_and_die "Failed to make directory ${dst_path}"

#curl -f https://raw.githubusercontent.com/bazel/bazel/master/scripts/get | \
#  bazel_INSTALL_DIR="$dst_path" bash -s - --version "v${version}" --no-sudo >&2 || error_and_die "Install failed"

#mkdir -p ${dst_path}/.bazel
wget -qO /tmp/bazel-${version}-installer-$(uname -s)-$(uname -m).sh https://github.com/bazelbuild/bazel/releases/download/${version}/bazel-${version}-installer-$(uname -s)-$(uname -m).sh
  ##TODO: make piped install work
  #bash -s - --prefix=${dst_path} --user >&2 || error_and_die "Install failed"
bash /tmp/bazel-${version}-installer-$(uname -s)-$(uname -m).sh --prefix=${dst_path} >&2 || error_and_die "Install failed"
ln -svnf ${dst_path} $HOME/.bazel


info "Installation of bazel v${version} successful"
