#!/usr/bin/env bash
#
# Summary: Set or show the global bazel version
#
# Usage: bazelenv global <version>
#
# Sets the global bazel version. You can override the global version at
# any time by setting a directory-specific version with `bazelenv local'
# or by setting the `BAZELENV_VERSION' environment variable.
#
# <version> should be a string matching a bazel version known to bazelenv.
# The special version string `system' will use your default system bazel.
# Run `bazelenv versions' for a list of available bazel versions.

set -e
[ -n "$BAZELENV_DEBUG" ] && set -x

# Provide bazelenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec bazelenv-versions --bare
fi

versions=("$@")
BAZELENV_VERSION_FILE="${BAZELENV_ROOT}/version"

if [ -n "$versions" ]; then
  bazelenv-version-file-write "$BAZELENV_VERSION_FILE" "${versions[@]}"
else
  OLDIFS="$IFS"
  IFS=: versions=($(
    bazelenv-version-file-read "$BAZELENV_VERSION_FILE" ||
    bazelenv-version-file-read "${BAZELENV_ROOT}/global" ||
    bazelenv-version-file-read "${BAZELENV_ROOT}/default" ||
    echo system
  ))
  IFS="$OLDIFS"
  for version in "${versions[@]}"; do
    echo "$version"
  done
fi
