#!/usr/bin/env bash
#
# Summary: Run bazel with the selected version
#
# Usage: bazelenv exec <command> [arg1 arg2...]
#
# Runs bazel or tiller by first preparing PATH so that the selected
# version's `bin' directory is at the front.
#
# For example, if the currently selected bazel version is 1.11.3:
#   bazelenv exec bazel version
#   bazelenv exec tiller -version
#
# is equivalent to:
#   PATH="$BAZELENV_ROOT/versions/1.11.3/bin:$PATH" bazel version

set -e
[ -n "${BAZELENV_DEBUG}" ] && set -x

export CMD=$1
if [ -z "${CMD}" ]; then
  echo "bazelenv: command is not specified" >&2
  exit 1
fi

shift

export BIN_PATH=$(bazelenv-bin-path)
if [ -z "${BIN_PATH}" ]; then
  exit 1
fi

export CMD_FULL="${BIN_PATH}/${CMD}"
if [ ! -x "${CMD_FULL}" ]; then
  echo "bazelenv: command not found: ${CMD}" >&2
  exit 1
fi

exec "${CMD_FULL}" "${@}"
